sudo: false
before_install:
  - bundle --version
  - gem --version
bundler_args: --without development --jobs 3 --retry 3
script: bundle exec rake spec
language: ruby
rvm:
  - 2.2
  - 1.9.3
branches:
  only:
    - master
    - 1-stable
